import unittest
import tempfile
import shutil
from pathlib import Path
import frontmatter
from stratasift.core.lifecycle import quarantine_file, shelve_file


class TestLifecycle(unittest.TestCase):
    """Unit tests for file lifecycle operations: quarantine and shelving.

    Uses British spelling rules.
    """

    def setUp(self) -> None:
        self.temp_dir = Path(tempfile.mkdtemp())

    def tearDown(self) -> None:
        if self.temp_dir.exists():
            shutil.rmtree(self.temp_dir)

        # Clean up global log file generated by test runs if it exists
        log_file = Path("stratasift.log")
        if log_file.exists():
            log_file.unlink()

    def test_quarantine_file(self) -> None:
        """Verify files are moved to the quarantine directory and collision is managed."""
        # Create a test file to quarantine
        source_file = self.temp_dir / "bad_paper.md"
        source_file.write_text("Malformed content.", encoding="utf-8")

        quarantine_dir = self.temp_dir / "quarantine"

        # Ingest/quarantine first time
        dest_path = quarantine_file(source_file, quarantine_dir, "Missing title")

        self.assertFalse(source_file.exists())
        self.assertTrue(dest_path.exists())
        self.assertEqual(dest_path.parent, quarantine_dir)
        self.assertEqual(dest_path.name, "bad_paper.md")

        # Verify log entry was written
        log_content = Path("stratasift.log").read_text(encoding="utf-8")
        self.assertIn("Failed to parse/validate clip 'bad_paper.md'", log_content)
        self.assertIn("Reason: Missing title", log_content)

        # Create same file name again to test collision
        source_file.write_text("Another bad content.", encoding="utf-8")
        dest_path_2 = quarantine_file(source_file, quarantine_dir, "Invalid yaml")

        self.assertTrue(dest_path_2.exists())
        self.assertNotEqual(dest_path_2.name, "bad_paper.md")
        self.assertTrue(dest_path_2.name.startswith("bad_paper_"))

    def test_shelve_file(self) -> None:
        """Verify files are moved to the Shelved vault area and frontmatter is updated."""
        # Create a test file to shelve
        source_file = self.temp_dir / "irrelevant_paper.md"
        source_file.write_text(
            "---\ntitle: Irrelevant Topic\n---\nPaper contents.", encoding="utf-8"
        )

        vault_dir = self.temp_dir / "vault"

        dest_path = shelve_file(source_file, vault_dir, 0.45)

        self.assertFalse(source_file.exists())
        self.assertTrue(dest_path.exists())
        self.assertEqual(dest_path.parent, vault_dir / "Shelved")
        self.assertEqual(dest_path.name, "irrelevant_paper.md")

        # Verify frontmatter updates
        post = frontmatter.load(dest_path)
        self.assertEqual(post.metadata.get("stratasift_status"), "shelved")
        self.assertEqual(post.metadata.get("relevance_score"), 0.45)
        self.assertIn("evaluated_at", post.metadata)


if __name__ == "__main__":
    unittest.main()
